services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ayaou\CommandLoggerBundle\:
    resource: '../src/*'
    exclude: '../src/{Entity}'

  Ayaou\CommandLoggerBundle\EventListener\CommandLogger\CommandStartListener:
    class: Ayaou\CommandLoggerBundle\EventListener\CommandLogger\CommandStartListener
    arguments:
      $enabled: '%command_logger.enabled%'
      $otherCommands: '%command_logger.commands%'
    tags:
      - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

  Ayaou\CommandLoggerBundle\EventListener\CommandLogger\CommandTerminateListener:
    class: Ayaou\CommandLoggerBundle\EventListener\CommandLogger\CommandTerminateListener
    arguments:
      $enabled: '%command_logger.enabled%'
      $otherCommands: '%command_logger.commands%'
    tags:
      - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate }

  Ayaou\CommandLoggerBundle\EventListener\CommandLogger\CommandErrorListener:
    class: Ayaou\CommandLoggerBundle\EventListener\CommandLogger\CommandErrorListener
    arguments:
      $enabled: '%command_logger.enabled%'
      $otherCommands: '%command_logger.commands%'
      $maxErrorMessageLength: '%command_logger.max_error_message_length%'
    tags:
      - { name: kernel.event_listener, event: console.error, method: onConsoleError }

  Ayaou\CommandLoggerBundle\Util\SensitiveParameterRedactor:
    arguments:
      $sensitiveParameters: '%command_logger.sensitive_parameters%'

  Ayaou\CommandLoggerBundle\Command\PurgeCommandLoggerTableCommand:
    arguments:
      $defaultPurgeThreshold: '%command_logger.purge_threshold%'

  Ayaou\CommandLoggerBundle\Util\CommandExecutionTracker:
    shared: true
