services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ayaou\CommandLoggerBundle\:
    resource: '../src/*'
    exclude: '../src/{Entity}'

  Ayaou\CommandLoggerBundle\EventListener\CommandStartListener:
    class: Ayaou\CommandLoggerBundle\EventListener\CommandStartListener
    arguments:
      $commandMap: !tagged_iterator console.command
      $enabled: '%command_logger.enabled%'
      $otherCommands: '%command_logger.commands%'
    tags:
      - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }

  Ayaou\CommandLoggerBundle\EventListener\CommandTerminateListener:
    class: Ayaou\CommandLoggerBundle\EventListener\CommandTerminateListener
    arguments:
      $commandMap: !tagged_iterator console.command
      $enabled: '%command_logger.enabled%'
      $otherCommands: '%command_logger.commands%'
    tags:
      - { name: kernel.event_listener, event: console.terminate, method: onConsoleTerminate }

  Ayaou\CommandLoggerBundle\EventListener\CommandErrorListener:
    class: Ayaou\CommandLoggerBundle\EventListener\CommandErrorListener
    arguments:
      $commandMap: !tagged_iterator console.command
      $enabled: '%command_logger.enabled%'
      $otherCommands: '%command_logger.commands%'
    tags:
      - { name: kernel.event_listener, event: console.error, method: onConsoleError }

  Ayaou\CommandLoggerBundle\Command\PurgeCommandLoggerTableCommand:
    arguments:
      $defaultPurgeThreshold: '%command_logger.purge_threshold%'

  Ayaou\CommandLoggerBundle\Util\CommandExecutionTracker:
    shared: true