name: Tests and Release

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

permissions:
  contents: write
  issues: write

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
        symfony-version: ['6.4.*', '7.0.*', '7.1.*', '7.2.*', '7.3.*']
        exclude:
          - php-version: '8.1'
            symfony-version: '7.0.*'
          - php-version: '8.1'
            symfony-version: '7.1.*'
          - php-version: '8.1'
            symfony-version: '7.2.*'
          - php-version: '8.1'
            symfony-version: '7.3.*'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: sqlite3, pdo_sqlite

      - name: Restrict Symfony version
        run: composer config extra.symfony.require "${{ matrix.symfony-version }}"
        if: matrix.symfony-version != ''

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: SYMFONY_DEPRECATIONS_HELPER=disabled vendor/bin/phpunit tests -d error_reporting="~E_DEPRECATED & ~E_USER_DEPRECATED"

  release:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github
      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}