name: Tests and Release

# Trigger the workflow on these events
on:
  push:
    branches:
      - '*'  # Run on push to any branch
  pull_request:
    branches:
      - '*'  # Run on PRs targeting any branch

# Set permissions for GITHUB_TOKEN
permissions:
  contents: write  # Needed for pushing tags and commits
  issues: write    # Optional, for @semantic-release/github to create failure issues

jobs:
  # Job 1: Run tests
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Clones the repo

      - name: Set up PHP
        uses: shivammathur/setup-php@v2  # Installs PHP 8.2
        with:
          php-version: '8.2'
          extensions: sqlite3, pdo_sqlite  # For Doctrine/SQLite in tests

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --dev  # Installs PHP deps

      - name: Run integration tests
        run: vendor/bin/phpunit tests/Integration  # Runs integration tests

      - name: Run unit tests
        run: vendor/bin/phpunit tests/Unit  # Runs unit tests

  # Job 2: Handle release (only on main)
  release:
    runs-on: ubuntu-latest
    needs: tests  # Only runs if tests pass
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only on main
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for commit analysis

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/github

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # For GitHub releases and tagging